---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: robdimsdale/concourse-pipeline-resource
    tag: latest-final


resources:
- name: my-pipelines
  type: concourse-pipeline
  source:
    target: http://192.168.100.4:8080
    insecure: "false"
    teams:
    - name: my-team
      username: ci
      password: changeme

- name: git-repository
  type: git
  source:
    uri: https://github.com/vspiewak/set-pipeline-test.git


jobs:
- name: set-my-pipelines
  plan:

  - get: git-repository
    trigger: true

  - put: my-pipelines
    params:
      pipelines:
      - name: my-pipeline
        team: my-team
        config_file: git-repository/pipeline.yaml
